name: build_test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - run: npm install -g corepack@latest
      - run: corepack enable
      - name: Set up node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
