name: design_tokens_test

on:
  pull_request:
    paths:
      - packages/designTokens/**
      - .github/workflows/design_tokens_test.yml
    branches:
      - main
  push:
    paths:
      - packages/designTokens/**
      - .github/workflows/design_tokens_test.yml
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: npm install -g corepack@latest
      - run: corepack enable
      - name: Set up node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Format
        run: pnpm format
        working-directory: ./packages/designTokens
