name: design_tokens_test

on:
  pull_request:
    paths:
      - packages/designTokens/**
      - .github/workflows/design_tokens_test.yml
    branches:
      - main
  push:
    paths:
      - packages/designTokens/**
      - .github/workflows/design_tokens_test.yml
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - run: npm install -g corepack@latest
      - run: corepack enable
      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Format
        run: pnpm format
        working-directory: ./packages/designTokens
