name: react_test

on:
  pull_request:
    paths:
      - packages/react/**
      - ".github/workflows/react_test.yml"
    branches:
      - main
  push:
    paths:
      - packages/react/**
      - ".github/workflows/react_test.yml"
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - run: npm install -g corepack@latest
      - run: corepack enable
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
        working-directory: ./packages/react
      - name: Markuplint
        run: pnpm lint:markuplint
        working-directory: ./packages/react
      - name: Format
        run: pnpm prettier
        working-directory: ./packages/react
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - run: npm install -g corepack@latest
      - run: corepack enable
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Test
        run: pnpm test
        working-directory: ./packages/react
